- params:
    git:
      repoName: devops-frogbot-examples
      branches:
        - frogbot-python
    scan:
      projects:
        - workingDirs:
            - ./python
          pipRequirementsFile: requirements.txt
